// Generated by tsbindgen - Architecture
// Namespace: Tsonic.JSRuntime
// Module Stub - Do Not Execute

throw new Error(
  'Cannot execute @tsonic/js directly in JavaScript. ' +
  'This package is a Tsonic source package and must be compiled by Tsonic.'
);
