import "./core-globals.js";
import "./globals.js";

// Generated by tsbindgen - Architecture
// Namespace: Tsonic.JSRuntime
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './index/internal/index.js';

// Primitive type aliases for flattened exports
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Cross-namespace type imports for constraints
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Action, Boolean as ClrBoolean, Byte, Comparison, Double, Exception, Func, Int16, Int32, Int64, Nullable, Object as ClrObject, SByte, Single, String as ClrString, UInt16, UInt32, ValueTuple, Void } from '@tsonic/dotnet/System.js';
import type { ISerializable } from '@tsonic/dotnet/System.Runtime.Serialization.js';

// Public JS constructor/object exports
export { ArrayBuffer as ArrayBuffer } from './index/internal/index.js';
export { Boolean$instance as Boolean } from './index/internal/index.js';
export { console$instance as console } from './index/internal/index.js';
export declare const Date: typeof Internal.Date;
export type Date = Internal.Date;
export { Error as Error } from './index/internal/index.js';
export { Float32Array as Float32Array } from './index/internal/index.js';
export { Float64Array as Float64Array } from './index/internal/index.js';
export { Int16Array as Int16Array } from './index/internal/index.js';
export { Int32Array as Int32Array } from './index/internal/index.js';
export { Int8Array as Int8Array } from './index/internal/index.js';
export { JSON$instance as JSON } from './index/internal/index.js';
export { Map_2 as Map } from './index/internal/index.js';
export { Math$instance as Math } from './index/internal/index.js';
export { Number$instance as Number } from './index/internal/index.js';
export { Object$instance as Object } from './index/internal/index.js';
export { RangeError as RangeError } from './index/internal/index.js';
export { RegExp as RegExp } from './index/internal/index.js';
export { RegExpMatchResult as RegExpMatchResult } from './index/internal/index.js';
export { Set_1 as Set } from './index/internal/index.js';
export { String$instance as String } from './index/internal/index.js';
export { Timers$instance as Timers } from './index/internal/index.js';
export { Uint16Array as Uint16Array } from './index/internal/index.js';
export { Uint32Array as Uint32Array } from './index/internal/index.js';
export declare const Uint8Array: typeof Internal.Uint8Array;
export type Uint8Array = Internal.Uint8Array;
export { Uint8ClampedArray as Uint8ClampedArray } from './index/internal/index.js';
export { WeakMap_2 as WeakMap } from './index/internal/index.js';
export { WeakSet_1 as WeakSet } from './index/internal/index.js';


// Flattened exports from static classes
// From Tsonic.JSRuntime.Globals
export declare function Boolean(value: unknown): boolean;
export declare function decodeURI(uri: string): string;
export declare function decodeURIComponent(component: string): string;
export declare function encodeURI(uri: string): string;
export declare function encodeURIComponent(component: string): string;
export declare function isFinite(value: double): boolean;
export declare function isFinite(value: int): boolean;
export declare function isFinite(value: Nullable<int>): boolean;
export declare function isFinite(value: long): boolean;
export declare function isFinite(value: Nullable<long>): boolean;
export declare function isNaN(value: double): boolean;
export declare function isNaN(value: int): boolean;
export declare function isNaN(value: Nullable<int>): boolean;
export declare function isNaN(value: long): boolean;
export declare function isNaN(value: Nullable<long>): boolean;
export declare function Number(value: unknown): double;
export declare function parseFloat(str: string): double;
export declare function parseInt(str: string, radix?: Nullable<int>): double;
export declare function String(value: unknown): string;
export declare const Infinity: double;
export declare const NaN: double;
export declare const undefined: unknown | undefined;
