// Generated by tsbindgen - Extension Method Tables
// This file contains method-table interfaces for C# extension methods.
// Tables are scoped by declaring namespace (C# using semantics).
// For each namespace with extension methods, this file exports an ExtensionMethods_<Namespace> helper.

// Import namespace modules for cross-namespace type references
import * as System from "@tsonic/dotnet/System/internal/index.js";

// Import primitive type aliases
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import sticky extension scope helper
import type { Rewrap } from '@tsonic/core/lang.js';

// Import CLR type aliases for generic type arguments
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";

// Import unsafe type markers
import type { ptr } from '@tsonic/core/types.js';

// Internal helper types for sticky extension scopes
type __TsonicExtMapOf<T> = T extends { __tsonic_ext?: infer M } ? M : {};
type __TsonicMergeExtMaps<A, B> = A & B;
type __TsonicWithExt<TShape, K extends string, TApplier> = { __tsonic_ext?: __TsonicMergeExtMaps<__TsonicExtMapOf<TShape>, { [P in K]: TApplier }> };

// Extension method table for namespace: Tsonic.JSRuntime
interface __TsonicExtMethods_Tsonic_JSRuntime {
  at(this: string, index: int): Rewrap<this, string>;
  charAt(this: string, index: int): Rewrap<this, string>;
  charCodeAt(this: string, index: int): Rewrap<this, int>;
  codePointAt(this: string, index: int): Rewrap<this, int>;
  concat(this: string, ...strings: string[]): Rewrap<this, string>;
  endsWith(this: string, searchString: string): Rewrap<this, boolean>;
  includes(this: string, searchString: string): Rewrap<this, boolean>;
  indexOf(this: string, searchString: string, position?: int): Rewrap<this, int>;
  isWellFormed(this: string): Rewrap<this, boolean>;
  lastIndexOf(this: string, searchString: string, position?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, int>;
  length(this: string): Rewrap<this, int>;
  localeCompare(this: string, compareString: string): Rewrap<this, int>;
  match(this: string, pattern: string): Rewrap<this, string[] | undefined>;
  matchAll(this: string, pattern: string): Rewrap<this, string[][]>;
  normalize(this: string, form?: string): Rewrap<this, string>;
  padEnd(this: string, targetLength: int, padString?: string): Rewrap<this, string>;
  padStart(this: string, targetLength: int, padString?: string): Rewrap<this, string>;
  repeat(this: string, count: int): Rewrap<this, string>;
  replace(this: string, search: string, replacement: string): Rewrap<this, string>;
  replaceAll(this: string, search: string, replacement: string): Rewrap<this, string>;
  search(this: string, pattern: string): Rewrap<this, int>;
  slice(this: string, start: int, end?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  split(this: string, separator: string, limit?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string[]>;
  startsWith(this: string, searchString: string): Rewrap<this, boolean>;
  substr(this: string, start: int, length?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  substring(this: string, start: int, end?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  toLocaleLowerCase(this: string): Rewrap<this, string>;
  toLocaleUpperCase(this: string): Rewrap<this, string>;
  toLowerCase(this: string): Rewrap<this, string>;
  toString(this: boolean): Rewrap<this, string>;
  toString(this: double): Rewrap<this, string>;
  toString(this: int): Rewrap<this, string>;
  toString(this: long): Rewrap<this, string>;
  toString(this: System.Nullable_1<System_Internal.Double>): Rewrap<this, string>;
  toString(this: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  toString(this: System.Nullable_1<System_Internal.Int64>): Rewrap<this, string>;
  toString(this: string): Rewrap<this, string>;
  toUpperCase(this: string): Rewrap<this, string>;
  toWellFormed(this: string): Rewrap<this, string>;
  trim(this: string): Rewrap<this, string>;
  trimEnd(this: string): Rewrap<this, string>;
  trimLeft(this: string): Rewrap<this, string>;
  trimRight(this: string): Rewrap<this, string>;
  trimStart(this: string): Rewrap<this, string>;
  valueOf(this: boolean): Rewrap<this, boolean>;
  valueOf(this: double): Rewrap<this, double>;
  valueOf(this: int): Rewrap<this, int>;
  valueOf(this: long): Rewrap<this, long>;
  valueOf(this: System.Nullable_1<System_Internal.Double>): Rewrap<this, System.Nullable_1<System_Internal.Double>>;
  valueOf(this: System.Nullable_1<System_Internal.Int32>): Rewrap<this, System.Nullable_1<System_Internal.Int32>>;
  valueOf(this: System.Nullable_1<System_Internal.Int64>): Rewrap<this, System.Nullable_1<System_Internal.Int64>>;
  valueOf(this: string): Rewrap<this, string>;
}

// Generic helper type for extension methods in namespace: Tsonic.JSRuntime
interface __TsonicExtApplier_Tsonic_JSRuntime {
  __tsonic_shape: unknown;
  __tsonic_type: __TsonicExtMethods_Tsonic_JSRuntime;
}

export type ExtensionMethods_Tsonic_JSRuntime<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & __TsonicWithExt<TShape, "Tsonic.JSRuntime", __TsonicExtApplier_Tsonic_JSRuntime> & __TsonicExtMethods_Tsonic_JSRuntime;

